# Generated by Django 5.1 on 2024-08-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venues', '0002_remove_venue_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(upload_to='venues/'),
        ),
    ]
