# Generated by Django 5.1 on 2024-08-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venues', '0003_alter_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='sports',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
    ]
