# Generated by Django 5.1 on 2024-08-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Venues', '0004_venue_sports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='sports',
        ),
    ]
