# Generated by Django 5.1.1 on 2024-09-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venues', '0007_alter_venue_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='sports',
            field=models.TextField(default='Cricket'),
        ),
    ]
