# Generated by Django 4.1.13 on 2024-09-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('venue_name', models.CharField(max_length=255)),
                ('sport', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
